# Generated by Django 5.2.6 on 2025-10-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_course_enrollment_course_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Announcement',
        ),
    ]
